name: Create Repositories

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9

      - name: List modified directories in Production
        id: list_modified_dirs
        run: |
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            modified_dirs=$(git diff --name-only HEAD Production | awk -F'/' '{print $2}' | sort -u)
          else
            modified_dirs=$(git diff --name-only HEAD~1 HEAD Production | awk -F'/' '{print $2}' | sort -u)
          fi
          echo "directories=$modified_dirs" >> $GITHUB_ENV

      - name: Terraform Apply
        run: |
          IFS=' ' read -r -a directories <<< "${{ env.directories }}"
          for directory in "${directories[@]}"; do
            echo "Applying Terraform in $directory"
            cd "Production/$directory"
            terraform init
            terraform apply -auto-approve
            cd ../..
          done
        env:
          TF_VAR_github_token: ${{ secrets.TOKEN_GITHUB }}